---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-microservice-b

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-microservice-b
  namespace: demo-microservice-b
  labels:
    app: demo-microservice-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-microservice-b
  template:
    metadata:
      labels:
        app: demo-microservice-b
    spec:
      containers:
        - name: demo-microservice
          image: dsuprunov/demo-microservice:0.1.0
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: SERVICE_ID
              value: demo-microservice-b
            - name: INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PEERS
              value: '["http://demo-microservice-a.demo-microservice-a:8000/ping"]'
            - name: INTERVAL
              value: "5"
            - name: TIMEOUT
              value: "2"
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http

---
apiVersion: v1
kind: Service
metadata:
  name: demo-microservice-b
  namespace: demo-microservice-b
  labels:
    app: demo-microservice-b
spec:
  selector:
    app: demo-microservice-b
  ports:
    - name: http
      port: 8000
      targetPort: http
